NAME: dbeaver
URL: https://github.com/dbeaver/dbeaver/tags
PARSER: html.parser
LINKS: true
ABSOLUTE_URLS: true
FILTERS:
  - REGEX: https://
  - NOT REGEX: http://
  - STARTS: https://
  - NOT STARTS: http://
  - CONTAINS: /refs/tags/
  - NOT CONTAINS: /foo/
  - ENDS: .tar.gz
  - NOT ENDS: .zip
STATUS: true
---
NAME: dbeaver_plugins
URL: https://dbeaver.io/update/ce/latest/plugins/
PARSER: html.parser
LINKS: false
FILTERS:
  - CONTAINS: .jar
STATUS: false
